### ISSUE TITLE
[FEAT]: Add mep data to data folder

### ISSUE THREAD

**Issue by DOH-PXC5303** [NW-PaGe/dstt_catalog_demo#14]
### Description

Add unstructured MEP data (pdf/word report?) to data folder to increase diversity of data types and team represented. Currently all our data are CSV which does not simulate real-world scenarios for data catalog use

**Comment by DOH-KGC0303** [comment]
I added the report to the data folder. Is there anything else I should do with it?

**Comment by DOH-PXC5303** [comment]
Awesome! @DOH-KGC0303 Could you also update the last row in [metadata.csv](https://github.com/NW-PaGe/dstt_catalog_demo/blob/main/metadata.csv)? I have a PR (#21) that moves the report you added into a subdirectory of `data/` and adds that location as a connection value in metadata.csv. The rest of the values (besides Product_ID) should be filled in. You can add whatever values you feel are appropriate for each field

**Comment by DOH-PXC5303** [comment]
Closed by #27
